# Generated by Django 2.1.2 on 2018-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='audio',
            name='embedded',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='length',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='narrated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='release_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='series',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='link',
            field=models.URLField(),
        ),
    ]
