# Generated by Django 2.1.2 on 2018-11-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20181113_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='desc',
            new_name='description',
        ),
    ]
